apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-cdp-securitycontext-cfg
  labels:
    app: cdp-securitycontext
webhooks:
  - name: mutating-cdp-securitycontext.datacreating.com
    clientConfig:
      service:
        name: cdp-securitycontext-svc
        namespace: jiexun-test
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: ds-parent-namespace
          operator: Exists
    timeoutSeconds: 5
