apiVersion: v1
kind: Service
metadata:
  name: cdp-securitycontext-svc
  labels:
    app: cdp-securitycontext
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: cdp-securitycontext
